// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBARTBrzNNtRAjrM4dFlzNgoUJILO_Va4k',
    appId: '1:285793972210:android:8bc6b338090a23a922856b',
    messagingSenderId: '285793972210',
    projectId: 'shoesmith-bus-app',
    storageBucket: 'shoesmith-bus-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4hwYpWYYA47E2DWUT-Ejo7AT472xGrJQ',
    appId: '1:285793972210:ios:df49d335ca59163522856b',
    messagingSenderId: '285793972210',
    projectId: 'shoesmith-bus-app',
    storageBucket: 'shoesmith-bus-app.appspot.com',
    androidClientId: '285793972210-sblqo2ltilpigq2cmthkvo3t7e8drneb.apps.googleusercontent.com',
    iosClientId: '285793972210-nbc53o0eil2r3ria2q3n7dp1e0fnjao1.apps.googleusercontent.com',
    iosBundleId: 'com.example.busapp',
  );
}
